# Generated by Django 4.2.27 on 2025-12-31 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plugins', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginEventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to='plugins.plugin')),
            ],
            options={
                'indexes': [models.Index(fields=['event_name', 'active'], name='plugin_even_event_n_df8119_idx')],
                'unique_together': {('plugin', 'event_name')},
            },
        ),
    ]
