# Generated by Django 4.2.27 on 2025-12-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plugin',
        ),
    ]
