#!/bin/bash

echo "Fraud Detection Testing Guide"
echo "============================="

echo ""
echo "1. SETUP FRAUD RULES"
echo "Run the following command to set up fraud detection rules:"
echo "python manage.py setup_fraud_detection"
echo ""

echo "2. START SERVICES"
echo "Terminal 1 - Django Server:"
echo "python manage.py runserver"
echo ""
echo "Terminal 2 - Kafka Consumer:"
echo "python manage.py consume_events"
echo ""

echo "3. FRAUD DETECTION TEST SCENARIOS"
echo ""

echo "SCENARIO 1: Multiple Terminals (Employee Login)"
echo "- Login with same employee from multiple browser tabs"
echo "- Expected: Fraud alert for multiple terminal usage"
echo ""

echo "SCENARIO 2: Rapid Item Addition"
echo "- Start a basket and add items very quickly (< 5 seconds apart)"
echo "- Add 5+ items rapidly"
echo "- Expected: Fraud alert for rapid item addition"
echo ""

echo "SCENARIO 3: High Value Payment (Short Session)"
echo "- Login and immediately start a basket"
echo "- Add high-value items (total > $500)"
echo "- Complete payment within 60 seconds of login"
echo "- Expected: Fraud alert for high-value payment in short session"
echo ""

echo "SCENARIO 4: Anonymous High-Value Payment"
echo "- Start a basket without customer lookup"
echo "- Add items totaling > $300"
echo "- Complete payment without identifying customer"
echo "- Expected: Fraud alert for anonymous high-value payment"
echo ""

echo "SCENARIO 5: Rapid Checkout"
echo "- Start a basket"
echo "- Add items and complete payment within 30 seconds"
echo "- Expected: Fraud alert for rapid checkout"
echo ""

echo "4. TESTING STEPS"
echo "a) Open frontend: http://localhost:3000"
echo "b) Login with: ankit@test.com / password123"
echo "c) Execute one of the scenarios above"
echo "d) Watch for fraud alert dialog to appear"
echo "e) Acknowledge the alert"
echo "f) Check Django logs for fraud detection messages"
echo ""

echo "5. MONITORING"
echo "- Browser console: WebSocket connection logs"
echo "- Django logs: Fraud detection plugin messages"
echo "- Database: Check fraud_alerts table for records"
echo ""

echo "6. MANUAL FRAUD ALERT TEST"
echo "To manually trigger a fraud alert for testing:"
echo "python manage.py shell"
echo ">>> from plugins.fraud_detection.plugin import FraudDetectionPlugin"
echo ">>> plugin = FraudDetectionPlugin()"
echo ">>> # Simulate event data and trigger alert"