# Generated by Django 4.2.27 on 2026-01-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_id', models.CharField(max_length=100)),
                ('source_product_id', models.CharField(max_length=50)),
                ('recommended_product_id', models.CharField(max_length=50)),
                ('recommended_product_name', models.CharField(max_length=200)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('was_accepted', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
    ]
