# Generated by Django 4.2.26 on 2026-01-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='reason',
            field=models.CharField(default='Frequently bought together', max_length=200),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
