# Generated by Django 4.2.26 on 2026-01-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_recommender', '0002_recommendation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='reason',
            field=models.CharField(blank=True, default='Frequently bought together', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True),
        ),
    ]
