# Generated by Django 4.2.26 on 2026-01-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_recommender', '0003_alter_recommendation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
