# Generated by Django 4.2.26 on 2026-01-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudalert',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
