# Generated by Django 4.2.26 on 2026-01-24 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeVerificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_id', models.CharField(max_length=100, unique=True)),
                ('requires_verification', models.BooleanField(default=False)),
                ('verification_completed', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verifier_employee_id', models.IntegerField(blank=True, null=True)),
                ('customer_age', models.IntegerField(blank=True, null=True)),
                ('verification_method', models.CharField(blank=True, max_length=50, null=True)),
                ('restricted_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'age_verification_states',
            },
        ),
        migrations.CreateModel(
            name='AgeVerificationViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('basket_id', models.CharField(max_length=100)),
                ('terminal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('violation_type', models.CharField(choices=[('UNVERIFIED_RESTRICTED_ITEMS', 'Unverified Restricted Items'), ('INSUFFICIENT_AGE', 'Insufficient Age'), ('INVALID_VERIFICATION', 'Invalid Verification'), ('SYSTEM_ERROR', 'System Error')], max_length=50)),
                ('details', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'age_verification_violations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
