# Generated by Django 4.2.27 on 2026-01-24 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'terminals',
                'indexes': [models.Index(fields=['employee', 'is_active'], name='terminals_employe_5089dc_idx')],
            },
        ),
    ]
