# Generated by Django 4.2.26 on 2026-01-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='age_restriction_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
